//! Python lock file file type plugin: core and presentation halves.
//!
//! Three tools lock Python dependencies and none of them write the same
//! file, though all three write TOML with `[[package]]` tables. Which
//! tool wrote one is therefore the first thing a reader needs told, and
//! the rest follows from it: `uv` records a resolution across several
//! environments at once, with markers deciding which packages apply
//! where; Poetry records one, with an `optional` flag per package.

use plugin_api::{Icon, PluginCore, PluginPresentation, Span};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::io;
use std::path::Path;
use syntax::{Language, Quote};

/// The lowercase extensions this type claims, without their dot.
///
/// Deliberately empty. These files are named `uv.lock`, `poetry.lock`
/// and `pdm.lock`, and `lock` belongs to the Cargo lock plugin; the
/// content decides this one.
pub const EXTENSIONS: &[&str] = &[];

/// How much of a lock file is read.
const READ_CAP: usize = 4 * 1024 * 1024;

/// How many packages are listed before the rest are only counted.
const SHOWN: usize = 64;

/// One locked package.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Package {
    /// Its name.
    pub name: String,
    /// The version locked.
    pub version: String,
    /// Where it comes from, read out.
    pub source: Option<String>,
    /// The marker expressions gating it or its dependencies - the
    /// conditions under which it is installed at all.
    pub markers: Vec<String>,
    /// How many built wheels are recorded for it.
    pub wheels: usize,
    /// Whether a source distribution is recorded too.
    pub source_distribution: bool,
    /// Whether it is only installed when an extra asks for it.
    pub optional: bool,
}

/// View data produced by [`PythonlockCore::view`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PythonlockView {
    /// Which tool wrote it.
    pub tool: String,
    /// The lock format's own version.
    pub lock_version: Option<String>,
    /// The Python the resolution is for.
    pub requires_python: Option<String>,
    /// The environments the resolution covers at once, when it covers
    /// more than one.
    pub resolution_markers: Vec<String>,
    /// The packages.
    pub packages: Vec<Package>,
    /// How many there are in all.
    pub package_count: usize,
    /// The hash tying it to the project file beside it.
    pub content_hash: Option<String>,
    /// Whether the file was longer than this reads.
    pub truncated: bool,
}

/// Whether `text` reads like a Python lock file.
///
/// A Cargo lock file is TOML with `[[package]]` tables too, so a
/// Python-only marker is asked for as well.
fn looks_like_it(text: &str) -> bool {
    let mut packages = 0usize;
    let mut python = false;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed == "[[package]]" {
            packages += 1;
        }
        for marker in [
            "requires-python",
            "resolution-markers",
            "python-versions",
            "lock-version",
            "generated by Poetry",
            "wheels = [",
            "sdist = {",
        ] {
            if trimmed.contains(marker) {
                python = true;
            }
        }
        if packages >= 1 && python {
            return true;
        }
    }
    false
}

/// The tool that wrote a lock file, from what only it writes.
fn tool_of(text: &str) -> &'static str {
    if text.contains("generated by Poetry") || text.contains("lock-version") {
        "Poetry"
    } else if text.contains("resolution-markers") || text.contains("[package.metadata]") {
        "uv"
    } else if text.contains("[metadata]\ngroups") || text.contains("pdm") {
        "PDM"
    } else {
        "an unrecognised tool"
    }
}

/// The value of a `key = value` line, unquoted.
fn value_of<'a>(line: &'a str, key: &str) -> Option<&'a str> {
    let rest = line.trim().strip_prefix(key)?.trim_start();
    Some(rest.strip_prefix('=')?.trim().trim_matches('"'))
}

/// The quoted strings in a run of text.
fn strings_in(text: &str) -> Vec<String> {
    let mut found = Vec::new();
    let mut rest = text;
    while let Some(open) = rest.find('"') {
        let after = &rest[open + 1..];
        let Some(close) = after.find('"') else { break };
        found.push(after[..close].to_owned());
        rest = &after[close + 1..];
    }
    found
}

/// A source, read out of the `source = { ... }` line both tools write
/// differently.
fn source_of(line: &str) -> Option<String> {
    let inside = line.split_once('{')?.1;
    let inside = inside.rsplit_once('}').map_or(inside, |(before, _)| before);
    let inside = inside.trim();
    if let Some(rest) = inside.strip_prefix("registry") {
        return Some(format!(
            "the registry at {}",
            strings_in(rest).first().cloned().unwrap_or_default()
        ));
    }
    if let Some(rest) = inside.strip_prefix("git") {
        return Some(format!(
            "git, at {}",
            strings_in(rest).first().cloned().unwrap_or_default()
        ));
    }
    if inside.starts_with("editable") {
        return Some("the project itself, installed editable".to_owned());
    }
    Some(inside.to_owned())
}

/// Everything [`PythonlockView`] holds, read from `source`.
fn parse(source: &str, truncated: bool) -> PythonlockView {
    let lines: Vec<&str> = source.lines().collect();
    let mut view = PythonlockView {
        tool: tool_of(source).to_owned(),
        lock_version: None,
        requires_python: None,
        resolution_markers: Vec::new(),
        packages: Vec::new(),
        package_count: 0,
        content_hash: None,
        truncated,
    };
    let mut current: Option<Package> = None;
    let mut in_resolution_markers = false;
    let mut in_wheels = false;
    // Whether the reader is inside one of a package's sub-tables. A
    // marker written in `[package.metadata]` belongs to a requirement
    // recorded there, not to the package: without this the project
    // itself came out gated on `extra == 'docs'`.
    let mut in_sub_table = false;

    for line in &lines {
        let trimmed = line.trim();
        if in_resolution_markers {
            if trimmed.starts_with(']') {
                in_resolution_markers = false;
            } else {
                view.resolution_markers.extend(strings_in(trimmed));
            }
            continue;
        }
        if trimmed == "[[package]]" {
            finish(&mut current, &mut view);
            current = Some(Package {
                name: String::new(),
                version: String::new(),
                source: None,
                markers: Vec::new(),
                wheels: 0,
                source_distribution: false,
                optional: false,
            });
            in_wheels = false;
            in_sub_table = false;
            continue;
        }
        if trimmed.starts_with("[package.") {
            in_sub_table = true;
        }
        // A table that is not `[[package]]` and not one of a
        // package's own sub-tables ends the package being read. Without
        // this the reader was still inside the last package when it
        // reached `[metadata]`, and missed what is written there.
        if trimmed.starts_with('[') && !trimmed.starts_with("[package") {
            finish(&mut current, &mut view);
            in_wheels = false;
        }
        if trimmed.starts_with("resolution-markers") {
            in_resolution_markers = !trimmed.contains(']');
            view.resolution_markers.extend(strings_in(trimmed));
            continue;
        }
        if let Some(python) = value_of(trimmed, "requires-python") {
            view.requires_python.get_or_insert(python.to_owned());
        }
        if let Some(python) = value_of(trimmed, "python-versions")
            && current.is_none()
        {
            view.requires_python.get_or_insert(python.to_owned());
        }
        if let Some(version) = value_of(trimmed, "lock-version") {
            view.lock_version = Some(version.to_owned());
        }
        if let Some(hash) = value_of(trimmed, "content-hash") {
            view.content_hash = Some(hash.to_owned());
        }
        if let Some(package) = &mut current {
            read_package_line(trimmed, package, &mut in_wheels, in_sub_table);
        } else if let Some(version) = value_of(trimmed, "version")
            && view.lock_version.is_none()
        {
            // `uv` writes the format version as a bare `version` at the
            // top, before any package.
            view.lock_version = Some(version.to_owned());
        }
    }
    finish(&mut current, &mut view);
    view
}

/// Reads one line belonging to the package being built.
fn read_package_line(
    trimmed: &str,
    package: &mut Package,
    in_wheels: &mut bool,
    in_sub_table: bool,
) {
    if *in_wheels {
        if trimmed.starts_with(']') {
            *in_wheels = false;
        } else if trimmed.contains("url = ") || trimmed.contains("file = ") {
            package.wheels += 1;
        }
        return;
    }
    if let Some(name) = value_of(trimmed, "name")
        && package.name.is_empty()
    {
        name.clone_into(&mut package.name);
    } else if let Some(version) = value_of(trimmed, "version")
        && package.version.is_empty()
    {
        version.clone_into(&mut package.version);
    } else if trimmed.starts_with("source = ") {
        package.source = source_of(trimmed);
    } else if trimmed.starts_with("optional = ") {
        package.optional = trimmed.ends_with("true");
    } else if trimmed.starts_with("sdist = ") {
        package.source_distribution = true;
    } else if trimmed.starts_with("wheels = [") || trimmed.starts_with("files = [") {
        *in_wheels = !trimmed.contains(']');
        // Poetry writes a source distribution as a `.tar.gz` among the
        // files rather than in an `sdist` of its own.
        if trimmed.contains(".tar.gz") {
            package.source_distribution = true;
        }
    } else if !in_sub_table && let Some(at) = trimmed.find("marker = ") {
        // Only the first string: the rest of the line carries the
        // dependency's version specifier, which is not a marker.
        package.markers.extend(
            strings_in(&trimmed[at + "marker = ".len()..])
                .into_iter()
                .take(1),
        );
    } else if !in_sub_table && trimmed.starts_with("markers = ") {
        package
            .markers
            .extend(strings_in(trimmed).into_iter().take(1));
    }
    if trimmed.contains(".tar.gz") {
        package.source_distribution = true;
    }
}

/// Files a finished package into the view.
fn finish(current: &mut Option<Package>, view: &mut PythonlockView) {
    let Some(package) = current.take() else {
        return;
    };
    if package.name.is_empty() {
        return;
    }
    view.package_count += 1;
    if view.packages.len() < SHOWN {
        view.packages.push(package);
    }
}

/// Everything [`PythonlockView`] holds, read from the file at `path`.
fn read(path: &Path) -> io::Result<PythonlockView> {
    let source = std::fs::read_to_string(path)?;
    let truncated = source.len() > READ_CAP;
    let source = if truncated {
        let mut end = READ_CAP;
        while end > 0 && !source.is_char_boundary(end) {
            end -= 1;
        }
        &source[..end]
    } else {
        source.as_str()
    };
    if !looks_like_it(source) {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "not a Python lock file",
        ));
    }
    Ok(parse(source, truncated))
}

/// The Python lock file plugin's core half.
#[derive(Debug, Default)]
pub struct PythonlockCore;

/// How this language is coloured, for the shared tokeniser. GUIDANCE.md
/// §3.6: the plugin describes its own format, the pane paints what it is
/// told.
const PYTHONLOCK: Language = Language {
    line_comment: &["#"],
    block_comment: &[],
    quotes: &[Quote::simple('"')],
    keywords: &["false", "true"],
    types: &[],
    calls: false,
    ignore_case: false,
};

impl PluginCore for PythonlockCore {
    fn name(&self) -> &'static str {
        "pythonlock"
    }

    fn extensions(&self) -> &'static [&'static str] {
        EXTENSIONS
    }

    fn specialises(&self) -> &'static [&'static str] {
        // A lock file is TOML, which `toml` recognises. This is the
        // narrower reading of the same bytes (D13).
        &["toml"]
    }

    fn sniff(&self, prefix: &[u8]) -> bool {
        std::str::from_utf8(prefix).is_ok_and(looks_like_it)
    }

    fn view(&self, path: &Path) -> io::Result<Value> {
        let view = read(path)?;
        serde_json::to_value(view).map_err(|err| io::Error::new(io::ErrorKind::InvalidData, err))
    }
}

/// The Python lock file plugin's presentation half.
#[derive(Debug, Default)]
pub struct PythonlockPresentation;

impl PluginPresentation for PythonlockPresentation {
    fn classify(&self, text: &str) -> Vec<Span> {
        syntax::classify(text, &PYTHONLOCK)
    }

    fn name(&self) -> &'static str {
        "pythonlock"
    }

    fn icon(&self) -> Icon {
        Icon {
            label: "LOCK",
            tint: 0x0030_6998,
        }
    }

    fn extensions(&self) -> &'static [&'static str] {
        EXTENSIONS
    }

    fn present(&self, data: &Value) -> Vec<String> {
        let view: PythonlockView = match serde_json::from_value(data.clone()) {
            Ok(view) => view,
            Err(err) => return vec![format!("could not read view data: {err}")],
        };
        let mut lines = vec![format!(
            "Python lock written by {}: {} package(s)",
            view.tool, view.package_count
        )];
        if let Some(version) = &view.lock_version {
            lines.push(format!("Lock format {version}"));
        }
        if let Some(python) = &view.requires_python {
            lines.push(format!("Resolved for Python {python}"));
        }
        if view.resolution_markers.is_empty() {
            lines.push("One environment.".to_owned());
        } else {
            lines.push("Resolved for several environments at once:".to_owned());
            for marker in &view.resolution_markers {
                lines.push(format!("  {marker}"));
            }
        }
        if let Some(hash) = &view.content_hash {
            lines.push(format!("Tied to a project file hashing to {hash}"));
        }
        lines.push("Packages:".to_owned());
        for package in &view.packages {
            let optional = if package.optional { " [optional]" } else { "" };
            lines.push(format!("  {} {}{optional}", package.name, package.version));
            if let Some(source) = &package.source {
                lines.push(format!("      from {source}"));
            }
            match (package.wheels, package.source_distribution) {
                (0, true) => lines.push("      source only: it has to be built".to_owned()),
                (0, false) => {}
                (wheels, true) => {
                    lines.push(format!("      {wheels} wheel(s), and the source"));
                }
                (wheels, false) => lines.push(format!("      {wheels} wheel(s)")),
            }
            for marker in &package.markers {
                lines.push(format!("      only when {marker}"));
            }
        }
        if view.package_count > view.packages.len() {
            lines.push(format!(
                "  ... and {} more",
                view.package_count - view.packages.len()
            ));
        }
        lines
    }
}

#[cfg(test)]
mod tests {
    use super::{
        PythonlockCore, PythonlockPresentation, PythonlockView, looks_like_it, source_of, tool_of,
    };
    use plugin_api::{PluginCore, PluginPresentation};

    fn sample(name: &str) -> std::path::PathBuf {
        std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../../samples/pythonlock")
            .join(name)
    }

    fn view_of(name: &str) -> PythonlockView {
        serde_json::from_value(PythonlockCore.view(&sample(name)).unwrap()).unwrap()
    }

    #[test]
    fn both_halves_claim_the_same_extensions() {
        assert_eq!(
            PluginCore::extensions(&PythonlockCore),
            PluginPresentation::extensions(&PythonlockPresentation),
            "one list, or a listing marks a file with a type its viewer will not open"
        );
    }

    #[test]
    fn it_says_it_specialises_the_toml_reading() {
        assert_eq!(PythonlockCore.specialises(), &["toml"]);
        assert!(PluginCore::extensions(&PythonlockCore).is_empty());
    }

    #[test]
    fn a_cargo_lock_is_toml_with_packages_too() {
        assert!(looks_like_it(
            "version = 1\nrequires-python = \">=3.9\"\n\n[[package]]\nname = \"a\"\n"
        ));
        assert!(
            !looks_like_it(
                "# This file is automatically @generated by Cargo.\nversion = 4\n\n\
                 [[package]]\nname = \"a\"\nversion = \"1\"\n"
            ),
            "a Cargo lock file has the tables and none of the Python"
        );
        assert!(!looks_like_it(""));
    }

    #[test]
    fn the_tool_is_named_by_what_only_it_writes() {
        assert_eq!(tool_of("resolution-markers = []"), "uv");
        assert_eq!(tool_of("# generated by Poetry 1.8.3"), "Poetry");
        assert_eq!(tool_of("nothing familiar"), "an unrecognised tool");
    }

    #[test]
    fn a_source_reads_out_as_where_it_came_from() {
        assert_eq!(
            source_of("source = { registry = \"https://pypi.org/simple\" }").as_deref(),
            Some("the registry at https://pypi.org/simple")
        );
        assert!(
            source_of("source = { git = \"https://example.com/a?rev=1\" }")
                .is_some_and(|said| said.starts_with("git, at https://example.com/a"))
        );
        assert_eq!(
            source_of("source = { editable = \".\" }").as_deref(),
            Some("the project itself, installed editable")
        );
    }

    #[test]
    fn reads_a_uv_lock() {
        let view = view_of("uv.lock");

        assert_eq!(view.tool, "uv");
        assert_eq!(view.lock_version.as_deref(), Some("1"));
        assert_eq!(view.requires_python.as_deref(), Some(">=3.9"));
        assert_eq!(view.package_count, 10);
        assert_eq!(
            view.resolution_markers.len(),
            2,
            "it resolves for two environments at once"
        );
    }

    #[test]
    fn reads_the_three_kinds_of_source_a_uv_lock_records() {
        let view = view_of("uv.lock");

        let named = |name: &str| {
            view.packages
                .iter()
                .find(|one| one.name == name)
                .expect("the package")
        };
        assert!(
            named("csvstats")
                .source
                .as_deref()
                .is_some_and(|said| said.contains("editable"))
        );
        assert!(
            named("click")
                .source
                .as_deref()
                .is_some_and(|said| said.contains("pypi.org"))
        );
        assert!(
            named("readings-fast")
                .source
                .as_deref()
                .is_some_and(|said| said.starts_with("git,")),
            "{:?}",
            named("readings-fast").source
        );
    }

    #[test]
    fn reads_the_wheels_and_the_source_distributions() {
        let view = view_of("uv.lock");

        let click = view
            .packages
            .iter()
            .find(|one| one.name == "click")
            .expect("click");
        assert_eq!(click.wheels, 1);
        assert!(click.source_distribution, "it records the tarball as well");

        let sphinx = view
            .packages
            .iter()
            .find(|one| one.name == "sphinx")
            .expect("sphinx");
        assert_eq!(sphinx.wheels, 0);
        assert!(
            sphinx.source_distribution,
            "source only: it has to be built"
        );
    }

    #[test]
    fn a_marker_in_a_metadata_table_belongs_to_the_requirement_not_the_package() {
        // Found by reading what the pane showed: the project itself came
        // out gated on `extra == 'docs'` and on `>=7.0` - which is a
        // version specifier, not a marker at all. Both were read out of
        // the `[package.metadata]` table beneath it.
        let view = view_of("uv.lock");

        let project = view
            .packages
            .iter()
            .find(|one| one.name == "csvstats")
            .expect("the project itself");
        assert!(project.markers.is_empty(), "{:?}", project.markers);
    }

    #[test]
    fn reads_the_markers_that_gate_a_package() {
        let view = view_of("uv.lock");

        let click = view
            .packages
            .iter()
            .find(|one| one.name == "click")
            .expect("click");
        assert!(
            click.markers.iter().any(|one| one.contains("win32")),
            "{:?}",
            click.markers
        );
    }

    #[test]
    fn reads_a_poetry_lock_and_says_so() {
        let view = view_of("poetry.lock");

        assert_eq!(view.tool, "Poetry");
        assert_eq!(view.lock_version.as_deref(), Some("2.0"));
        assert_eq!(view.requires_python.as_deref(), Some("^3.9"));
        assert_eq!(view.package_count, 4);
        assert_eq!(
            view.content_hash.as_deref(),
            Some("0c1b2a3d4e5f60718293a4b5c6d7e8f901a2b3c4d5e6f708192a3b4c5d6e7f80")
        );
        assert!(
            view.resolution_markers.is_empty(),
            "Poetry resolves for one environment"
        );
    }

    #[test]
    fn an_optional_package_is_told_from_a_required_one() {
        let view = view_of("poetry.lock");

        let sphinx = view
            .packages
            .iter()
            .find(|one| one.name == "sphinx")
            .expect("the optional package");
        assert!(sphinx.optional);
        assert!(
            view.packages
                .iter()
                .filter(|one| one.name != "sphinx")
                .all(|one| !one.optional)
        );
    }

    #[test]
    fn presents_the_tool_first_because_the_shape_follows_from_it() {
        let uv = PythonlockPresentation.present(&PythonlockCore.view(&sample("uv.lock")).unwrap());
        let poetry =
            PythonlockPresentation.present(&PythonlockCore.view(&sample("poetry.lock")).unwrap());

        assert!(uv[0].starts_with("Python lock written by uv: 10 package(s)"));
        assert!(
            uv.iter()
                .any(|line| line.contains("Resolved for several environments at once"))
        );
        assert!(
            uv.iter()
                .any(|line| line.contains("only when sys_platform == 'win32'"))
        );

        assert!(poetry[0].starts_with("Python lock written by Poetry: 4 package(s)"));
        assert!(poetry.iter().any(|line| line.contains("One environment.")));
        assert!(poetry.iter().any(|line| line.contains("[optional]")));
    }

    #[test]
    fn a_file_that_is_not_a_lock_file_is_an_error_rather_than_a_panic() {
        let path = std::env::temp_dir().join("not-really-uv.lock");
        std::fs::write(&path, b"nothing of the sort at all").unwrap();

        assert!(PythonlockCore.view(&path).is_err());
        let _ = std::fs::remove_file(&path);
    }
}
