<#
.SYNOPSIS
Installs or uninstalls Repos Explorer for the current user on Windows.

.DESCRIPTION
Install downloads one release's graphical application, terminal application
and service for this machine, verifies every file against the release's
signed update manifest before placing anything, and puts the three side by
side in a per-user folder. No administrator rights are needed.

Verification is the scheme the in-application updater uses: each file's
Secure Hash Algorithm 256 (SHA-256) digest must match the manifest, and the
manifest's Ed25519 signature over that digest must verify against the public
key compiled into the release's `verify` program. That program is itself
checked against its manifest digest before it is run, and verifies itself
along with the rest.

Uninstall stops application and service processes started from the install
folder, removes what install placed, and says what it removed. -Purge also
removes the per-user data folder (the journal, the Repos Directory
configuration and window settings), and refuses unless -Yes is given or the
CI environment variable is "true".

.PARAMETER Tag
The release to install, for example v0.7.0. Default: latest, read from the
manifest the updater itself polls.

.PARAMETER FromDirectory
Install from a folder of already-built release files and their
manifest.json instead of downloading them: the release workflow's check of a
release before it is published.

.PARAMETER UnsignedTestManifest
With -FromDirectory only. Checks digests but NOT signatures, for a manifest a
developer generated by hand to test this script without the signing key. Never
use it for anything you mean to run.

.PARAMETER Prefix
Where to install. Default: %LOCALAPPDATA%\Programs\RepoSphereExplorer.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File install.ps1
powershell -ExecutionPolicy Bypass -File install.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [string]$Tag = 'latest',
    [string]$FromDirectory,
    [switch]$UnsignedTestManifest,
    [string]$Prefix = (Join-Path $env:LOCALAPPDATA 'Programs\RepoSphereExplorer'),
    [switch]$Uninstall,
    [switch]$Purge,
    [switch]$Yes
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

$Repository = 'StewartScottRogers/RepoSphereExplorer'
$LatestManifestUrl = 'https://stewartscottrogers.github.io/RepoSphereExplorer/latest.json'
$Installed = @('RepoSphereExplorerGui', 'RepoSphereExplorerTui', 'service')
$Receipt = 'installed-files.txt'
$DataDirectory = Join-Path $env:LOCALAPPDATA 'RepoSphereExplorer'

$TagGiven = $PSBoundParameters.ContainsKey('Tag')

function Fail([string]$Message) {
    throw "install.ps1: $Message"
}

function Stop-ProcessesIn([string]$Folder) {
    $root = [IO.Path]::GetFullPath($Folder).TrimEnd('\') + '\'
    $running = @(Get-Process | Where-Object {
            $_.Path -and $_.Path.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)
        })
    foreach ($process in $running) {
        Write-Output "stopped $($process.Path) (process $($process.Id))"
        Stop-Process -Id $process.Id -Force
    }
    if ($running.Count -gt 0) {
        $running | Wait-Process -Timeout 15 -ErrorAction SilentlyContinue
    }
}

# Deletes a file, waiting for Windows to let go of it.
#
# An executable that has just been stopped is still locked for a moment after
# the process is gone, so an uninstall run while the application was open
# failed with "access to the path is denied" and left the install behind. The
# same happens when an antivirus scanner is reading a file as it is removed.
function Remove-FileWhenUnlocked([string]$Path) {
    for ($attempt = 1; $attempt -le 40; $attempt++) {
        try {
            Remove-Item -LiteralPath $Path -Force -ErrorAction Stop
            return
        }
        catch [System.UnauthorizedAccessException], [System.IO.IOException] {
            if ($attempt -eq 40) { throw }
            Start-Sleep -Milliseconds 250
        }
    }
}

function Invoke-Uninstall {
    $receiptPath = Join-Path $Prefix $Receipt
    if (-not (Test-Path -LiteralPath $receiptPath)) {
        Fail "nothing installed by this script at $Prefix (no $Receipt there)"
    }
    if ($Purge -and -not $Yes -and $env:CI -ne 'true') {
        Fail ("refusing -Purge: it deletes $DataDirectory, which holds this machine's journal " +
            "and Repos Directory configuration. Run again with -Yes if that is what you want.")
    }

    Stop-ProcessesIn $Prefix
    foreach ($path in Get-Content -LiteralPath $receiptPath) {
        if ($path -and (Test-Path -LiteralPath $path)) {
            Remove-FileWhenUnlocked $path
            Write-Output "removed $path"
        }
    }
    Remove-FileWhenUnlocked $receiptPath
    $left = @(Get-ChildItem -LiteralPath $Prefix -Force)
    if ($left.Count -eq 0) {
        Remove-Item -LiteralPath $Prefix -Force
        Write-Output "removed $Prefix"
    }
    else {
        Write-Output "left $Prefix in place; it still holds: $(($left | ForEach-Object Name) -join ', ')"
    }

    if ($Purge) {
        if (Test-Path -LiteralPath $DataDirectory) {
            Stop-ProcessesIn $DataDirectory
            foreach ($item in Get-ChildItem -LiteralPath $DataDirectory -Force -Recurse) {
                Write-Output "removed $($item.FullName)"
            }
            Remove-Item -LiteralPath $DataDirectory -Recurse -Force
            Write-Output "removed $DataDirectory"
        }
        else {
            Write-Output "no data folder at $DataDirectory"
        }
    }
}

function Get-Target {
    if ($env:PROCESSOR_ARCHITECTURE -eq 'AMD64') { return 'x86_64-pc-windows-msvc' }
    Fail "no release is built for Windows on $env:PROCESSOR_ARCHITECTURE"
}

function Get-File([string]$Url, [string]$Destination) {
    try {
        Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $Destination
    }
    catch {
        Fail "could not download ${Url}: $($_.Exception.Message)"
    }
}

function Invoke-Install {
    if ($TagGiven -and $FromDirectory) {
        Fail '-Tag and -FromDirectory cannot be used together'
    }
    if ($UnsignedTestManifest -and -not $FromDirectory) {
        Fail '-UnsignedTestManifest is only for a local -FromDirectory test'
    }
    if (Test-Path -LiteralPath (Join-Path $Prefix $Receipt)) {
        Fail "Repos Explorer is already installed at $Prefix; uninstall it first"
    }
    $target = Get-Target
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $staging = Join-Path ([IO.Path]::GetTempPath()) ("rse-install-" + [Guid]::NewGuid())
    New-Item -ItemType Directory -Path $staging | Out-Null
    try {
        $manifestPath = Join-Path $staging 'manifest.json'
        if ($FromDirectory) {
            $source = Join-Path $FromDirectory 'manifest.json'
            if (-not (Test-Path -LiteralPath $source)) { Fail "no manifest.json in $FromDirectory" }
            Copy-Item -LiteralPath $source -Destination $manifestPath
        }
        elseif ($Tag -eq 'latest') {
            Get-File $LatestManifestUrl $manifestPath
        }
        else {
            Get-File "https://github.com/$Repository/releases/download/$Tag/manifest.json" $manifestPath
        }
        $manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
        Write-Output "release $($manifest.version) for $target"

        $wanted = $Installed
        if (-not $UnsignedTestManifest) { $wanted = $Installed + 'verify' }
        $assets = @{}
        $missing = @()
        foreach ($binary in $wanted) {
            $asset = $manifest.targets | Where-Object { $_.binary -eq $binary -and $_.target -eq $target } |
                Select-Object -First 1
            if ($asset) { $assets[$binary] = $asset } else { $missing += $binary }
        }
        if ($missing.Count -gt 0) {
            $published = ($manifest.targets | Where-Object { $_.target -eq $target } |
                ForEach-Object binary) -join ', '
            Fail ("release $($manifest.version) publishes no $($missing -join ', ') for $target " +
                "(it publishes: $published)")
        }

        $files = @{}
        foreach ($binary in $wanted) {
            $asset = $assets[$binary]
            $name = $asset.url.Substring($asset.url.LastIndexOf('/') + 1)
            $file = Join-Path $staging $name
            if ($FromDirectory) {
                $source = Join-Path $FromDirectory $name
                if (-not (Test-Path -LiteralPath $source)) { Fail "no $name in $FromDirectory" }
                Copy-Item -LiteralPath $source -Destination $file
            }
            else {
                Get-File $asset.url $file
            }
            $digest = (Get-FileHash -Algorithm SHA256 -LiteralPath $file).Hash.ToLowerInvariant()
            if ($digest -ne $asset.sha256.ToLowerInvariant()) {
                Fail "refusing ${name}: its digest does not match the manifest, so it is not the file that was released"
            }
            $files[$binary] = $file
        }

        if ($UnsignedTestManifest) {
            Write-Warning 'SIGNATURES NOT CHECKED (-UnsignedTestManifest): digests only, against a manifest nobody signed.'
        }
        else {
            $verify = $files['verify']
            & $verify $manifestPath @($wanted | ForEach-Object { $files[$_] })
            if ($LASTEXITCODE -ne 0) {
                Fail 'refusing to install: signature verification failed'
            }
        }

        New-Item -ItemType Directory -Force -Path $Prefix | Out-Null
        $placed = @()
        foreach ($binary in $Installed) {
            $destination = Join-Path $Prefix "$binary.exe"
            Copy-Item -LiteralPath $files[$binary] -Destination $destination -Force
            $placed += $destination
            Write-Output "placed $destination"
        }
        Set-Content -LiteralPath (Join-Path $Prefix $Receipt) -Value $placed -Encoding UTF8
        Write-Output "installed Repos Explorer $($manifest.version) in $Prefix"
        Write-Output "run: & '$(Join-Path $Prefix 'RepoSphereExplorerGui.exe')'"
    }
    finally {
        Remove-Item -LiteralPath $staging -Recurse -Force -ErrorAction SilentlyContinue
    }
}

try {
    if ($Purge -and -not $Uninstall) { Fail '-Purge only goes with -Uninstall' }
    if ($Uninstall) { Invoke-Uninstall } else { Invoke-Install }
}
catch {
    [Console]::Error.WriteLine($_.Exception.Message)
    exit 1
}
exit 0
