<#
.SYNOPSIS
Installs or uninstalls Repos Explorer for the current user on Windows.

.DESCRIPTION
Install downloads one release's graphical application, terminal application
and service for this machine, verifies every file against the release's
signed update manifest before placing anything, and puts the three side by
side in a per-user folder. No administrator rights are needed.

It then tells Windows the application is here: a "Repos Explorer" shortcut in
the Start menu pointing at the graphical application, and a per-user entry in
Settings > Apps whose Uninstall button runs this script back. A copy of this
script is placed in the install folder for that button to run, because the
script is downloaded rather than installed and the downloaded copy may be
gone by then.

Verification is the scheme the in-application updater uses: each file's
Secure Hash Algorithm 256 (SHA-256) digest must match the manifest, and the
manifest's Ed25519 signature over that digest must verify against the public
key compiled into the release's `verify` program. That program is itself
checked against its manifest digest before it is run, and verifies itself
along with the rest.

Uninstall stops application and service processes started from the install
folder, removes what install placed - the files, the Start menu shortcut and
the Settings > Apps entry, each one read back from the receipt install wrote,
so it removes exactly those and nothing else - and says what it removed.
-Purge also removes the per-user data folder (the journal, the Repos
Directory configuration and window settings), and refuses unless -Yes is
given or the CI environment variable is "true".

.PARAMETER Tag
The release to install, for example v0.7.0. Default: latest, read from the
manifest the updater itself polls.

.PARAMETER FromDirectory
Install from a folder of already-built release files and their
manifest.json instead of downloading them: the release workflow's check of a
release before it is published.

.PARAMETER UnsignedTestManifest
With -FromDirectory only. Checks digests but NOT signatures, for a manifest a
developer generated by hand to test this script without the signing key. Never
use it for anything you mean to run.

.PARAMETER Prefix
Where to install. Default: %LOCALAPPDATA%\Programs\RepoSphereExplorer.

The layout - that folder, the file names, the receipt, the Start menu
shortcut and the Settings > Apps entry - is shared with ReposExplorerSetup,
the setup program a reader can download instead of this script. One
definition, in crates/setup/src/layout.rs, renders the generated block below;
`cargo test -p setup` fails if the two have drifted, so both ways in install
the same thing.

.PARAMETER StartMenuDirectory
Install only. Where the Start menu shortcut goes. Default: this user's Start
menu Programs folder.

.PARAMETER UninstallRegistryKey
Install only. The registry key for the Settings > Apps entry, under
HKEY_CURRENT_USER (HKCU), this user's own hive. Default:
HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\ReposExplorer.

Both exist for the same reason -Prefix does: a second copy installed beside
the real one - the release check's self-update test - points them somewhere
harmless so it does not take over the first copy's Start menu shortcut and
Apps entry. Uninstall needs neither: it reads both back from the receipt.

.EXAMPLE
powershell -ExecutionPolicy Bypass -File install.ps1
powershell -ExecutionPolicy Bypass -File install.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [string]$Tag = 'latest',
    [string]$FromDirectory,
    [switch]$UnsignedTestManifest,
    [string]$Prefix,
    [string]$StartMenuDirectory,
    [string]$UninstallRegistryKey,
    [switch]$Uninstall,
    [switch]$Purge,
    [switch]$Yes
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

# --- generated from crates/setup/src/layout.rs ---
# One definition of what an install is, shared with the setup program:
# `crates/setup/src/layout.rs` renders this block, and `cargo test -p setup`
# fails if the copy below has drifted from it. Edit that file, not this block.
$Installed = @('RepoSphereExplorerGui', 'RepoSphereExplorerTui', 'service')
$Receipt = 'installed-files.txt'
$Application = 'Repos Explorer'
$Publisher = 'Stewart Scott Rogers'
$Summary = 'Repos Explorer - a front door to the working copies your source control checks code out into'
# A receipt line is a path to remove, unless it starts with this, in which
# case the rest of it is a registry key to remove. install.sh writes paths
# only; nothing outside Windows reads or writes a line of this shape.
$RegistryLine = 'registry:'
if (-not $Prefix) { $Prefix = Join-Path $env:LOCALAPPDATA 'Programs\RepoSphereExplorer' }
if (-not $StartMenuDirectory) { $StartMenuDirectory = Join-Path $env:APPDATA 'Microsoft\Windows\Start Menu\Programs' }
if (-not $UninstallRegistryKey) { $UninstallRegistryKey = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\ReposExplorer' }
# --- end generated ---

$Repository = 'StewartScottRogers/RepoSphereExplorer'
$LatestManifestUrl = 'https://stewartscottrogers.github.io/RepoSphereExplorer/latest.json'
$DataDirectory = Join-Path $env:LOCALAPPDATA 'RepoSphereExplorer'
$UninstallScript = 'install.ps1'

$TagGiven = $PSBoundParameters.ContainsKey('Tag')

function Fail([string]$Message) {
    throw "install.ps1: $Message"
}

function Stop-ProcessesIn([string]$Folder) {
    $root = [IO.Path]::GetFullPath($Folder).TrimEnd('\') + '\'
    $running = @(Get-Process | Where-Object {
            $_.Path -and $_.Path.StartsWith($root, [StringComparison]::OrdinalIgnoreCase)
        })
    foreach ($process in $running) {
        Write-Output "stopped $($process.Path) (process $($process.Id))"
        Stop-Process -Id $process.Id -Force
    }
    if ($running.Count -gt 0) {
        $running | Wait-Process -Timeout 15 -ErrorAction SilentlyContinue
    }
}

# Deletes a file, waiting for Windows to let go of it.
#
# An executable that has just been stopped is still locked for a moment after
# the process is gone, so an uninstall run while the application was open
# failed with "access to the path is denied" and left the install behind. The
# same happens when an antivirus scanner is reading a file as it is removed.
function Remove-FileWhenUnlocked([string]$Path) {
    for ($attempt = 1; $attempt -le 40; $attempt++) {
        try {
            Remove-Item -LiteralPath $Path -Force -ErrorAction Stop
            return
        }
        catch [System.UnauthorizedAccessException], [System.IO.IOException] {
            if ($attempt -eq 40) { throw }
            Start-Sleep -Milliseconds 250
        }
    }
}

function Invoke-Uninstall {
    $receiptPath = Join-Path $Prefix $Receipt
    if (-not (Test-Path -LiteralPath $receiptPath)) {
        Fail "nothing installed by this script at $Prefix (no $Receipt there)"
    }
    if ($Purge -and -not $Yes -and $env:CI -ne 'true') {
        Fail ("refusing -Purge: it deletes $DataDirectory, which holds this machine's journal " +
            "and Repos Directory configuration. Run again with -Yes if that is what you want.")
    }

    Stop-ProcessesIn $Prefix
    foreach ($line in Get-Content -LiteralPath $receiptPath) {
        if (-not $line) { continue }
        if ($line.StartsWith($RegistryLine)) {
            $key = $line.Substring($RegistryLine.Length)
            if (Test-Path -LiteralPath $key) {
                Remove-Item -LiteralPath $key -Recurse -Force
                Write-Output "removed $key"
            }
        }
        elseif (Test-Path -LiteralPath $line) {
            Remove-FileWhenUnlocked $line
            Write-Output "removed $line"
        }
    }
    Remove-FileWhenUnlocked $receiptPath
    $left = @(Get-ChildItem -LiteralPath $Prefix -Force)
    if ($left.Count -eq 0) {
        Remove-Item -LiteralPath $Prefix -Force
        Write-Output "removed $Prefix"
    }
    else {
        Write-Output "left $Prefix in place; it still holds: $(($left | ForEach-Object Name) -join ', ')"
    }

    if ($Purge) {
        if (Test-Path -LiteralPath $DataDirectory) {
            Stop-ProcessesIn $DataDirectory
            foreach ($item in Get-ChildItem -LiteralPath $DataDirectory -Force -Recurse) {
                Write-Output "removed $($item.FullName)"
            }
            Remove-Item -LiteralPath $DataDirectory -Recurse -Force
            Write-Output "removed $DataDirectory"
        }
        else {
            Write-Output "no data folder at $DataDirectory"
        }
    }
}

# The Start menu shortcut, pointing at the installed graphical application.
#
# The icon is the executable's own, so nothing has to be placed beside the
# shortcut for it. An executable carrying no icon resource yet degrades
# quietly to the generic one Windows draws for any program.
function New-Shortcut([string]$Path, [string]$Executable) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    $shell = New-Object -ComObject WScript.Shell
    try {
        $link = $shell.CreateShortcut($Path)
        $link.TargetPath = $Executable
        $link.WorkingDirectory = $Prefix
        $link.Description = $Summary
        $link.IconLocation = "$Executable,0"
        $link.Save()
    }
    finally {
        [Runtime.InteropServices.Marshal]::ReleaseComObject($shell) | Out-Null
    }
}

# The Settings > Apps entry, under this user's hive: no administrator rights,
# and no claim on anyone else's account.
#
# UninstallString is what the Uninstall button runs, so it must still work
# long after the downloaded copy of this script is gone: it runs the copy
# install placed in $Prefix, against $Prefix.
function Register-Application([string]$Key, [string]$Executable, [string]$Uninstaller, [string]$Version, [int]$Kilobytes) {
    $powershell = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
    $values = [ordered]@{
        DisplayName     = $Application
        DisplayVersion  = $Version
        Publisher       = $Publisher
        DisplayIcon     = $Executable
        InstallLocation = $Prefix
        UninstallString = "`"$powershell`" -NoProfile -ExecutionPolicy Bypass -File `"$Uninstaller`" -Uninstall -Prefix `"$Prefix`""
    }
    New-Item -Path $Key -Force | Out-Null
    foreach ($name in $values.Keys) {
        New-ItemProperty -Path $Key -Name $name -Value $values[$name] -PropertyType String -Force | Out-Null
    }
    New-ItemProperty -Path $Key -Name 'EstimatedSize' -Value $Kilobytes -PropertyType DWord -Force | Out-Null
    foreach ($name in @('NoModify', 'NoRepair')) {
        New-ItemProperty -Path $Key -Name $name -Value 1 -PropertyType DWord -Force | Out-Null
    }
}

function Get-Target {
    if ($env:PROCESSOR_ARCHITECTURE -eq 'AMD64') { return 'x86_64-pc-windows-msvc' }
    Fail "no release is built for Windows on $env:PROCESSOR_ARCHITECTURE"
}

function Get-File([string]$Url, [string]$Destination) {
    try {
        Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $Destination
    }
    catch {
        Fail "could not download ${Url}: $($_.Exception.Message)"
    }
}

function Invoke-Install {
    if ($TagGiven -and $FromDirectory) {
        Fail '-Tag and -FromDirectory cannot be used together'
    }
    if ($UnsignedTestManifest -and -not $FromDirectory) {
        Fail '-UnsignedTestManifest is only for a local -FromDirectory test'
    }
    if (Test-Path -LiteralPath (Join-Path $Prefix $Receipt)) {
        Fail "Repos Explorer is already installed at $Prefix; uninstall it first"
    }
    if (-not $PSCommandPath) {
        Fail ('run this from a saved file (powershell -ExecutionPolicy Bypass -File install.ps1): install places a ' +
            'copy of the script in the install folder for the Uninstall button to run, and a script piped straight ' +
            'into PowerShell has no file to copy')
    }
    $target = Get-Target
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $staging = Join-Path ([IO.Path]::GetTempPath()) ("rse-install-" + [Guid]::NewGuid())
    New-Item -ItemType Directory -Path $staging | Out-Null
    try {
        $manifestPath = Join-Path $staging 'manifest.json'
        if ($FromDirectory) {
            $source = Join-Path $FromDirectory 'manifest.json'
            if (-not (Test-Path -LiteralPath $source)) { Fail "no manifest.json in $FromDirectory" }
            Copy-Item -LiteralPath $source -Destination $manifestPath
        }
        elseif ($Tag -eq 'latest') {
            Get-File $LatestManifestUrl $manifestPath
        }
        else {
            Get-File "https://github.com/$Repository/releases/download/$Tag/manifest.json" $manifestPath
        }
        $manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
        Write-Output "release $($manifest.version) for $target"

        $wanted = $Installed
        if (-not $UnsignedTestManifest) { $wanted = $Installed + 'verify' }
        $assets = @{}
        $missing = @()
        foreach ($binary in $wanted) {
            $asset = $manifest.targets | Where-Object { $_.binary -eq $binary -and $_.target -eq $target } |
                Select-Object -First 1
            if ($asset) { $assets[$binary] = $asset } else { $missing += $binary }
        }
        if ($missing.Count -gt 0) {
            $published = ($manifest.targets | Where-Object { $_.target -eq $target } |
                ForEach-Object binary) -join ', '
            Fail ("release $($manifest.version) publishes no $($missing -join ', ') for $target " +
                "(it publishes: $published)")
        }

        $files = @{}
        foreach ($binary in $wanted) {
            $asset = $assets[$binary]
            $name = $asset.url.Substring($asset.url.LastIndexOf('/') + 1)
            $file = Join-Path $staging $name
            if ($FromDirectory) {
                $source = Join-Path $FromDirectory $name
                if (-not (Test-Path -LiteralPath $source)) { Fail "no $name in $FromDirectory" }
                Copy-Item -LiteralPath $source -Destination $file
            }
            else {
                Get-File $asset.url $file
            }
            $digest = (Get-FileHash -Algorithm SHA256 -LiteralPath $file).Hash.ToLowerInvariant()
            if ($digest -ne $asset.sha256.ToLowerInvariant()) {
                Fail "refusing ${name}: its digest does not match the manifest, so it is not the file that was released"
            }
            $files[$binary] = $file
        }

        if ($UnsignedTestManifest) {
            Write-Warning 'SIGNATURES NOT CHECKED (-UnsignedTestManifest): digests only, against a manifest nobody signed.'
        }
        else {
            $verify = $files['verify']
            & $verify $manifestPath @($wanted | ForEach-Object { $files[$_] })
            if ($LASTEXITCODE -ne 0) {
                Fail 'refusing to install: signature verification failed'
            }
        }

        New-Item -ItemType Directory -Force -Path $Prefix | Out-Null
        $placed = @()
        foreach ($binary in $Installed) {
            $destination = Join-Path $Prefix "$binary.exe"
            Copy-Item -LiteralPath $files[$binary] -Destination $destination -Force
            $placed += $destination
            Write-Output "placed $destination"
        }

        $gui = Join-Path $Prefix 'RepoSphereExplorerGui.exe'
        $uninstaller = Join-Path $Prefix $UninstallScript
        Copy-Item -LiteralPath $PSCommandPath -Destination $uninstaller -Force
        $placed += $uninstaller
        Write-Output "placed $uninstaller"

        $shortcut = Join-Path $StartMenuDirectory "$Application.lnk"
        New-Shortcut $shortcut $gui
        $placed += $shortcut
        Write-Output "placed $shortcut"

        $kilobytes = [int](((@($placed) | ForEach-Object { (Get-Item -LiteralPath $_).Length }) |
                Measure-Object -Sum).Sum / 1KB)
        Register-Application $UninstallRegistryKey $gui $uninstaller $manifest.version $kilobytes
        Write-Output "registered $UninstallRegistryKey"

        Set-Content -LiteralPath (Join-Path $Prefix $Receipt) `
            -Value ($placed + ($RegistryLine + $UninstallRegistryKey)) -Encoding UTF8
        Write-Output "installed Repos Explorer $($manifest.version) in $Prefix"
        Write-Output "run: & '$gui', or Repos Explorer in the Start menu"
    }
    finally {
        Remove-Item -LiteralPath $staging -Recurse -Force -ErrorAction SilentlyContinue
    }
}

try {
    if ($Purge -and -not $Uninstall) { Fail '-Purge only goes with -Uninstall' }
    if ($Uninstall) { Invoke-Uninstall } else { Invoke-Install }
}
catch {
    [Console]::Error.WriteLine($_.Exception.Message)
    exit 1
}
exit 0
