platform :osx, "12.0"

target "DownloadQueue" do
  use_frameworks!

  target "DownloadQueueTests" do
    inherit! :search_paths
  end
end

post_install do |installation|
  installation.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["MACOSX_DEPLOYMENT_TARGET"] = "12.0"
      config.build_settings["GCC_TREAT_WARNINGS_AS_ERRORS"] = "YES"
    end
  end
end
